### ISSUE TITLE
"Cake: Install a configuration file" command produces server error

### ISSUE THREAD

**Issue by reicheltp** [cake-build/cake-vscode#13]
I have tried to use the "Cake: Install a configuration file" within vscode but instead of  an expected configuration file it created a `cake.config` file with a server error page inside:

``` html
<!DOCTYPE html>
<html>
    <head>
        <title>The current identity (IIS APPPOOL\cakebuild) does not have write access to 'D:\local\Temporary ASP.NET Files'.</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} 
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </style>
    </head>

    <body bgcolor="white">

            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>The current identity (IIS APPPOOL\cakebuild) does not have write access to 'D:\local\Temporary ASP.NET Files'.</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

            <br><br>

            <b> Exception Details: </b>System.Web.HttpException: The current identity (IIS APPPOOL\cakebuild) does not have write access to 'D:\local\Temporary ASP.NET Files'.<br><br>

            <b>Source Error:</b> <br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code>

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.</code>

                  </td>
               </tr>
            </table>

            <br>

            <b>Stack Trace:</b> <br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

[HttpException (0x80004005): The current identity (IIS APPPOOL\cakebuild) does not have write access to &#39;D:\local\Temporary ASP.NET Files&#39;.]
   System.Web.HttpRuntime.SetUpCodegenDirectory(CompilationSection compilationSection) +10003412
   System.Web.HttpRuntime.HostingInit(HostingEnvironmentFlags hostingFlags, PolicyLevel policyLevel, Exception appDomainCreationException) +204

[HttpException (0x80004005): The current identity (IIS APPPOOL\cakebuild) does not have write access to &#39;D:\local\Temporary ASP.NET Files&#39;.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9947380
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +261
</pre></code>

                  </td>
               </tr>
            </table>

            <br>

            <hr width=100% size=1 color=silver>

            <b>Version Information:</b>&nbsp;Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1055.0

            </font>

    </body>
</html>
<!-- 
[HttpException]: The current identity (IIS APPPOOL\cakebuild) does not have write access to &#39;D:\local\Temporary ASP.NET Files&#39;.
   at System.Web.HttpRuntime.SetUpCodegenDirectory(CompilationSection compilationSection)
   at System.Web.HttpRuntime.HostingInit(HostingEnvironmentFlags hostingFlags, PolicyLevel policyLevel, Exception appDomainCreationException)
[HttpException]: The current identity (IIS APPPOOL\cakebuild) does not have write access to &#39;D:\local\Temporary ASP.NET Files&#39;.
   at System.Web.HttpRuntime.FirstRequestInit(HttpContext context)
   at System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context)
   at System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context)
--><!-- 
This error page might contain sensitive information because ASP.NET is configured to show verbose error messages using &lt;customErrors mode="Off"/&gt;. Consider using &lt;customErrors mode="On"/&gt; or &lt;customErrors mode="RemoteOnly"/&gt; in production environments.-->
```

---
### Environment

Windows 10 Enterprise
VS Code 1.3.1
Cake Plugin 0.4.0

**Comment by gep13** [comment]
@reicheltp the cake website is currently down, so what you are seeing is the 404 page that is being returned from the request.

This is something we should really handle within the extension.

**Comment by patriksvensson** [comment]
@reicheltp Site is back up. Closing issue. Reopen if problem persists.

**Comment by patriksvensson** [comment]
Reopened the issue after @gep13 pointed out to me that the underlying issue needs to be fixed as well :smile:

**Comment by gep13** [comment]
This has now been corrected on the Cake Website:

https://github.com/cake-build/website/issues/380

And should be working again soon.
