### ISSUE TITLE
Problem debugging with this extension

### ISSUE THREAD

**Issue by pshrosbree** [cake-build/cake-vscode#53]
I'd appreciate any help getting debugging to work. I F5 in VSCode 1.15.1 32-bit on a cake script (that works) I get:

```
Processing build script...
Installing addins...
Loaded 'g:\mc\Schema\tools\Cake.CoreCLR\NuGet.Frameworks.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'g:\mc\Schema\tools\Cake.CoreCLR\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Error: System.InvalidOperationException: Something went wrong when parsing framework.
   at Cake.NuGet.V3.NuGetV3ContentResolver.ParseFromDirectoryPath(NuGetFramework current, DirectoryPath path)
   at Cake.NuGet.V3.NuGetV3ContentResolver.GetAddinAssemblies(DirectoryPath path)
   at Cake.NuGet.NuGetPackageInstaller.Install(PackageReference package, PackageType type, DirectoryPath path)
   at Cake.Core.Scripting.ScriptProcessor.InstallAddins(ScriptAnalyzerResult analyzerResult, DirectoryPath installPath)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.DebugCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
The program '[39968] Cake.dll' has exited with code 1 (0x1).
```

Cake 0.2.1.1
Cake.CoreCLR 0.21.1

**Comment by gep13** [comment]
@pshrosbree can you share the script you are trying to debug?

**Comment by pshrosbree** [comment]
```#addin nuget:?https://www.nuget.org/api/v2&package=Cake.Git&version=0.15.0

var target = Argument("target", "Default");

Task("Default")
    .Does(() => 
    { 
    });

RunTarget(target);```

I have discovered that if I omit the `#addin` I can debug.

**Comment by gep13** [comment]
Okay, so this makes sense.

As of today, when debugging in VSCode, you are using Cake.CoreCLR, which means all addins have to also be compiled for .net core. Cake.Git currently isn't. In the next version of Cake, 0.22.0, you will be able to use the mono debugger in VSCode, which means you will be able to debug addins that target .net framework.

Hope that makes sense.

**Comment by pshrosbree** [comment]
Thanks.

This only affects debugging, right? The scripts themselves seem to work just fine so far.

I am just starting to look at Cake as a replacement for our current build tool, so I am a newbie.

**Comment by gep13** [comment]
Yes, that is correctly. It only affects the debugging. Script will execute normally using Cake.exe.
